### ISSUE TITLE
Cannot get email from Facebook

### ISSUE THREAD

**Issue by danielhomola** [wooyek/flask-social-blueprint#10]
Hi,

Thanks so much for this blueprint, and for your work in general.

I couldn't get Facebook to work neither ("Could not register: Cannot create new user, authentication provider did not not provide email"), and even if I try it on: 
http://flask-social-blueprint.appspot.com/login?next=%2F

I get the following message: 
"App Not Set Up: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions."

Do you have any suggestions how to overcome this?

Thanks a lot,
Daniel

**Comment by wooyek** [comment]
Please check if it's ok now

**Comment by danielhomola** [comment]
The reason people still don't get last name and first name (see newest issue) is because you only solved half of the problem. You should explicitly request ALL fields from the new GraphAPI not just the email. This is why I asked you to please change line 138 in providers.py to:
profile = graph.get_object("me?fields=email,first_name,last_name,name")

**Comment by wooyek** [comment]
See #19 for name related problems
