### ISSUE TITLE
Email and register not Working

### ISSUE THREAD

**Issue by reginaldojunior** [wooyek/flask-social-blueprint#11]
Email not send when a register is done, show message "KeyError ['mail']". In page of example too show a error from server.

http://flask-social-blueprint.appspot.com/register

**Comment by wooyek** [comment]
It's out of scope of this project. The examples are here to demonstrate social based login/registration and are not designed to be a fully functional websites.

Please see:

https://pythonhosted.org/Flask-Security/quickstart.html#id4
